---
url: "https://petstore.swagger.io/v2/swagger.json"
dom_id: "#swagger-ui"
validatorUrl: "https://validator.swagger.io/validator"
requestInterceptor: "(request) => { request.credentials = 'include'; return request;}"